# Generated by Django 4.1.4 on 2023-01-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='costumer',
        ),
    ]
