# Generated by Django 4.1.4 on 2023-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_client_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
