# Generated by Django 4.1.4 on 2023-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.BooleanField(),
        ),
    ]
