# Generated by Django 4.1.4 on 2023-01-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_location_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locales'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
