# Generated by Django 4.1.4 on 2023-01-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_costumer_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='products', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
